# NumPy Basics By Phalguni Rathod
## Generation Notebook

#### Hi, Here we all we do and learn Numpy with hands-on implementaion. This tutorial have have 5 parts as follows:
1. Generation
2. Attributes & Functions
3. Slicing
4. Conditional Selection
5. Operations

In [2]:
import numpy as np

## Creation/ Generation
### From a Python List

In [3]:
#Array from list
my_py_list = [1,2,3]
my_py_list

[1, 2, 3]

In [4]:
np.array(my_py_list)

array([1, 2, 3])

In [5]:
#from 2D List/Matrix
my_mat = [[1,2,3],
         [4,5,6]]
my_mat

[[1, 2, 3], [4, 5, 6]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

## Built-in ways
Numpy have many ways to create arrays by itself

### zeros(dim) and ones(dim)
Numpy have builtin functions to generate and return arrays of zeros or ones.
We just have to pass the dimensions required.

In [11]:
#Zeros 1D
arr = np.zeros(7)
arr

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
#Zeros 2D
arr = np.zeros((2,3))
arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
#Ones 1D
arr1 = np.ones(7)
arr1

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
#Ones 2D
arr2 = np.ones((2,3))
arr2

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### eye(dim)
This method creates and return identity matrix of dimension passed as arugument.

In [25]:
np.eye(7)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.]])

### arange(start,stop,step)
It is simila to range() of Python.
It returns evenly spaced values within a given interval.

In [8]:
arr = np.arange(0,7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [26]:
arr = np.arange(5,30,5)
arr

array([ 5, 10, 15, 20, 25])

### linspace(start, stop, no.of items)
Return linearly/evenly spaced numbers over a specified interval.

In [30]:
np.linspace(0,20,5)

array([  0.,   5.,  10.,  15.,  20.])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [31]:
np.random.rand(2)

array([ 0.94248346,  0.16539956])

In [32]:
np.random.rand(5,5)

array([[ 0.6141018 ,  0.74940808,  0.17332572,  0.35069861,  0.59628926],
       [ 0.93174621,  0.86243002,  0.4103409 ,  0.10710342,  0.52560344],
       [ 0.97632113,  0.64696483,  0.74786802,  0.63106143,  0.46572643],
       [ 0.23411967,  0.52220032,  0.6298253 ,  0.12709664,  0.63550527],
       [ 0.32800311,  0.13779592,  0.87436783,  0.27819461,  0.07186522]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [33]:
np.random.randn(2)

array([ 1.53030272,  0.8378298 ])

In [34]:
np.random.randn(5,5)

array([[ 0.05273655,  0.2646446 ,  2.36136486, -0.4418797 , -1.82658035],
       [-1.50222621,  0.1687752 , -1.8848241 , -0.06556413,  1.51119328],
       [ 0.04966327, -1.03576807, -0.17359833,  0.35792389, -0.33911063],
       [ 2.12496572, -0.01360397, -1.38233848,  0.49599133,  1.49119452],
       [-0.86525824, -0.24214582,  1.89422861,  0.40580789,  0.10346574]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [35]:
np.random.randint(1,100)

99

In [36]:
np.random.randint(1,100,10)

array([ 9, 58, 88, 27, 20, 42, 34,  6, 37, 23])