# NumPy Basics By Phalguni Rathod
## Condtional Seletion Notebook

#### Hi, Here we all we do and learn Numpy with hands-on implementaion. This tutorial have have 5 parts as follows:
1. Generation
2. Attributes & Functions
3. Slicing
4. Conditional Selection
5. Operations

In [11]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr > 7

array([False, False, False, False, False, False, False,  True,  True,  True], dtype=bool)

In [6]:
bool_arr = arr>7

In [7]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,  True], dtype=bool)

In [8]:
arr[bool_arr]

array([ 8,  9, 10])

In [9]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
x = 4
arr[arr>x]

array([ 5,  6,  7,  8,  9, 10])

# Happy Learning!
