In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
import numpy as np

In [4]:
tensor_1d=np.array([1.45,-1])

In [6]:
type(tensor_1d)

numpy.ndarray

In [ ]:
# convert to tensor

In [7]:
tensor=tf.convert_to_tensor(tensor_1d , dtype=tf.float64)

In [8]:
tensor

<tf.Tensor 'Const:0' shape=(2,) dtype=float64>

In [ ]:
# one dim

In [9]:
d0=tf.ones((1,))

In [10]:
d0

<tf.Tensor 'ones:0' shape=(1,) dtype=float32>

In [12]:
sess=tf.Session()

In [13]:
print(sess.run(tensor))

[ 1.45 -1.  ]


In [ ]:
# 2 dimmension tensor

In [19]:
arr=np.array([(1,5,5,3,15),(10,20,30,40,50),(60,70,80,90,100)])

In [20]:
type(arr)

numpy.ndarray

In [25]:
arr.ndim

2

#### tf.convert_to_tensor()

In [21]:
tensor2d=tf.convert_to_tensor(arr)

In [22]:
tensor2d

<tf.Tensor 'Const_1:0' shape=(3, 5) dtype=int64>

In [23]:
sess=tf.Session()
print(sess.run(tensor2d))

[[  1   5   5   3  15]
 [ 10  20  30  40  50]
 [ 60  70  80  90 100]]


### Performing Maths operation

In [26]:
arr1=np.array([(1,2,3),(4,5,6)])

In [28]:
arr2=np.array([(7,8,9),(10,11,12)])

In [29]:
arr3=tf.add(arr1,arr2)

In [30]:
arr3

<tf.Tensor 'Add:0' shape=(2, 3) dtype=int64>

In [31]:
sess=tf.Session()
tensor=sess.run(arr3)

In [32]:
print(tensor)

[[ 8 10 12]
 [14 16 18]]


#### multiplication 

In [33]:
arr3=tf.multiply(arr1,arr2)

In [34]:
tensor=sess.run(arr3)

In [35]:
print(tensor)

[[ 7 16 27]
 [40 55 72]]


#### Build a graph

In [36]:
a=tf.constant(5.0)

In [37]:
b=tf.constant(6.0)

In [38]:
c=a*b

In [39]:
c

<tf.Tensor 'mul_1:0' shape=() dtype=float32>

In [41]:
sess=tf.Session()

In [42]:
output=sess.run(c)

In [43]:
print(output)

30.0


In [44]:
sess.close()

#### Creating a placeholder

In [46]:
a=tf.placeholder(tf.float32)

In [47]:
b=tf.placeholder(tf.float32)

In [48]:
mul=a*b

In [49]:
sess=tf.Session()

In [51]:
output=sess.run(mul,{a:[1,3,5],b:[2,4,5]})

In [52]:
print( "Multipliction of a & b : " , output)

Multipliction of a & b :  [ 2. 12. 25.]
