Pandas and Numpy need to be loaded as packages using import statements

import pandas as pd
import numpy as np

ideally upon installing anaconda these packages should be automatically loaded. just like jupyter.
in case there are issues, please follow the below steps

left click Windows Start ==> on the applications pane ==> click on anaconda ==> click on anaconda prompt ==> in the prompt type 
===> conda install pandas==> pandas will get installed

===> conda install numpy  ===> numpy will get installed




Pandas Data Structures

Series - one dimensional arrays 
         different from numpy arrays as in series we can assign our own index

Dataframe - 2 dimensional arrays
           - similar to a database table
           - assign our own indexes
           
           
Most of the work in real life gets accomplished via data frames and numpy arrays.



In [2]:
import pandas as pd

In [3]:
import numpy as np

### Let us create different python objects



In [4]:
##### new list called  "labels" with strings
labels = ['a','b','c','d','e']

In [5]:
#### create a new list of numbers
my_data = [10,20,30,40,50]

In [6]:
#### create a new numpy array out of the list my_data
myarr = np.array(my_data)

In [7]:
### create a dictionary
mydict = {'key1':10, 'key2':20, 'key3':100,'key4':40,'key5':50}

In [10]:
### print everything
print(labels)
print(my_data)
print(myarr)
print(mydict)

['a', 'b', 'c', 'd', 'e']
[10, 20, 30, 40, 50]
[10 20 30 40 50]
{'key1': 10, 'key2': 20, 'key3': 100, 'key4': 40, 'key5': 50}


### CREATING A PANDAS SERIES  USING PYTHON OBJECTS

In [11]:
### create a new series
### series takes a lot of parameters. but we will ONLY focus on parameters called "data" and "index"
### There are a few ways to create a series

In [15]:
## method 1 - create a series out of a list my_data with no index parameter passed to series
my_series0 = pd.Series(data=my_data)

In [17]:
print(my_series0)
print(type(my_series0))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [19]:
### create a series with "data " parameter from  my_data list and we want to change the index parameter using "labels" list
my_series1 = pd.Series(data=my_data,index=labels)
print(my_series1)

### note user defined index

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [21]:
### another way of creating a series - no need to give data= , index=
my_series2 = pd.Series(my_data,labels)
print(my_series2)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [22]:
### create a series from a tuple
## create my_tup
my_tup = ((1,2),('aa','bb'),(3,4),('cc','dd'),(50,60))
my_tup_series = pd.Series(data=my_tup,index=labels)
print(my_tup_series)

a      (1, 2)
b    (aa, bb)
c      (3, 4)
d    (cc, dd)
e    (50, 60)
dtype: object


In [23]:
my_tup = ((1,2),('aa','bb'),(3,4),('cc','dd'))
my_tup_series1 = pd.Series(data=my_tup,index=labels)
print(my_tup_series)

### indexes and contents need to align/match

ValueError: Length of passed values is 4, index implies 5

In [26]:
## create a series by using numpy array and labeled index 
my_ser3 = pd.Series(data=myarr,index=labels)
print(my_ser3)

a    10
b    20
c    30
d    40
e    50
dtype: int32


In [28]:
myarr 

array([10, 20, 30, 40, 50])

In [29]:
myarr[0]

10

In [31]:
### creating sreies from numpy array without index parameter
my_ser4 = pd.Series(myarr)
print(my_ser4)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [34]:
### create a series from a dictionary
print(mydict)

mylabel = ['python','scala','java','c++','cobol']

print(mylabel)

{'key1': 10, 'key2': 20, 'key3': 100, 'key4': 40, 'key5': 50}
['python', 'scala', 'java', 'c++', 'cobol']


In [43]:
### create series from dictionary, without index= parameter
my_series_5 = pd.Series(data=mydict)
print(my_series_5)

### note the indexes have been replaced by keys of dictionary.

key1     10
key2     20
key3    100
key4     40
key5     50
dtype: int64


In [45]:
mydict

{'key1': 10, 'key2': 20, 'key3': 100, 'key4': 40, 'key5': 50}

In [47]:
mydict['key1']

10

In [40]:
### create a series with index= parameter and pass the list "mylabel" as index
my_series_6 = pd.Series(data=mydict,index=mylabel)
print(my_series_6)

###NaN is Not a Number - or its missing value
### the original keys of dictionary are not displayed
### only the keys in the index= parameter are displayed - (from the list "mylabel")
### since these keys('python,scala,java,c++ ..') do not have necessary data, the data values for these keys are 
### represented a missing values or Nan or Not a Number
### so NO NEEED OF INDEXES for data= dict

python   NaN
scala    NaN
java     NaN
c++      NaN
cobol    NaN
dtype: float64


In [41]:
mylabel1 = ['key1', 'key2', 'key3', 'key4', 'key5']

In [48]:
### create a series with index= parameter and pass the list "mylabel" as index
my_series_7 = pd.Series(data=mydict,index=mylabel1)
print(my_series_7)

key1      10.0
key2      20.0
key3     100.0
key4      40.0
keey5      NaN
dtype: float64


In [46]:
mylabel[4] = 'key5'

In [47]:
mylabel

['python', 'scala', 'java', 'c++', 'key5']

In [48]:
my_series_7 = pd.Series(data=mydict,index=mylabel)
print(my_series_7)

python     NaN
scala      NaN
java       NaN
c++        NaN
key5      50.0
dtype: float64


### Getting data from Series

In [49]:
### 
myseries_8 = pd.Series(data=[1,2,3,4],index=['dog','cat','cow','pig'])

### data is 1,2,3,4 and index is dog, cat, cow and pig

In [51]:
print(myseries_8)

dog    1
cat    2
cow    3
pig    4
dtype: int64


In [54]:
### to get the value 4
myseries_8['pig']

4

In [66]:
myseries_9 = pd.Series(data=[100,200,300,400,399,599,199],index=['indx1','indx2','indx3','indx4','indx5','indx6','indx7'])
print(myseries_9)

indx1    100
indx2    200
indx3    300
indx4    400
indx5    399
indx6    599
indx7    199
dtype: int64


In [68]:
myseries_9[0]

100

In [62]:
myseries_91 = pd.Series(data=[100,200,300,400,399,599,199],index=[1,2,3,4,5,6,7])
print(myseries_91)

1    100
2    200
3    300
4    400
5    399
6    599
7    199
dtype: int64


In [71]:
myseries_91[7]

199

In [72]:
### we will get a key error in this case
myseries_91[0]

KeyError: 0

In [73]:
myseries_9['indx6']

599

In [57]:
myseries_9[5]

599

In [58]:
### create numpy array with country names
np_country = np.array(['china','india','senegal','tanzania','nigeria','costa rica','fiji','samoa','indonesia','germany'])

In [74]:
### create a series with np_country
series_country = pd.Series(data=np_country)
print(series_country)

0         china
1         india
2       senegal
3      tanzania
4       nigeria
5    costa rica
6          fiji
7         samoa
8     indonesia
9       germany
dtype: object


In [75]:
### create an array of labels
np_country_labels = np.array(['lab1','lab2','lab3','lab4','lab5','lab6','lab7','lab8','lab9','lab10'])

In [76]:
## create a new series with labels
series_country1 = pd.Series(data=np_country, index=np_country_labels)
print(series_country1)

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object


In [77]:
###alternate ways of accessing data from a series using .loc
print(series_country1.loc['lab1'])

china


In [78]:
print(series_country1['lab1'])

china


In [79]:
print(series_country1[0])

china


In [80]:
print(series_country1.iloc[0])

china


### SCALAR SERIES


In [83]:
series_scalar = pd.Series(data=500,index=['a','b','c','d'])
print(series_scalar)

### filled the value in data for all the indexes
### like broadcasting in numpy

a    500
b    500
c    500
d    500
dtype: int64


In [86]:
series_scalar1 = pd.Series(500,['a','b','c','d'])
print(series_scalar1)

a    500
b    500
c    500
d    500
dtype: int64


In [89]:
series_scalar = pd.Series(data=>500,index=['a','b','c','d'])
print(series_scalar)

SyntaxError: invalid syntax (<ipython-input-89-d7b2ab8cde59>, line 1)

In [97]:
mylistscalar = [100,800,911,499,501]
mylistscalararr = np.array(mylistscalar)
print(mylistscalararr)

[100 800 911 499 501]


In [100]:
### get all values greater than 500
mylistscalararr[mylistscalararr>500]

array([800, 911, 501])

In [104]:
series_scalar6 = pd.Series(data=mylistscalararr[mylistscalararr>500],index= ('scal1','scal2','scal3'))

In [103]:
print(series_scalar6)

scal1    800
scal2    911
scal3    501
dtype: int32


In [107]:
series_country1

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object

In [108]:
### slice notation in series

In [109]:
series_country1['lab1':'lab3']        ### unlike typical slice notation, the ending index is included

lab1      china
lab2      india
lab3    senegal
dtype: object

In [112]:
### other way using .loc
series_country1.loc['lab1':'lab3']   ### unlike typical slice notation, the ending index is included

lab1      china
lab2      india
lab3    senegal
dtype: object

In [115]:
series_country1[0:3] ###  typical slice notation works for default indexes only

lab1      china
lab2      india
lab3    senegal
dtype: object

In [121]:
series_country1.iloc[0:3]

lab1      china
lab2      india
lab3    senegal
dtype: object

In [117]:
series_country1[['lab1','lab3']]

### extracting using comma notation - grabbing individual values

lab1      china
lab3    senegal
dtype: object

In [118]:
series_country1

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object

In [123]:
series_country1[['lab1','lab4']]
### note the comma here

lab1       china
lab4    tanzania
dtype: object

In [124]:
series_country1[['lab5','lab7']]


lab5    nigeria
lab7       fiji
dtype: object

### operations in series (vectorized operations)


In [125]:
ser_1_vec = pd.Series([100,200,300,400,500],index=['i1','i2','i3','i4','i5'])

In [126]:
ser_2_vec = pd.Series([500,1000,3000,5000,8000],index=['i6','i7','i1','i2','i8'])

In [127]:
ser_3_vec = pd.Series([1000,2000,3000,400,500],index=['i1','i10','i13','i14','i15'])

In [128]:
## add 2 series

ser_1_vec + ser_2_vec

i1    3100.0
i2    5200.0
i3       NaN
i4       NaN
i5       NaN
i6       NaN
i7       NaN
i8       NaN
dtype: float64

In [129]:
ser_1_vec * ser_2_vec

i1     300000.0
i2    1000000.0
i3          NaN
i4          NaN
i5          NaN
i6          NaN
i7          NaN
i8          NaN
dtype: float64

In [131]:
### COMPARISONS OF SERIES
ser_1_vec > ser_2_vec

### the comparison will fail becausee the series objects need to be identically labeled. meaning the indexes need to be the same

ValueError: Can only compare identically-labeled Series objects

In [132]:
ser_3_vec = pd.Series([99,299,399,499,9],index=['i1','i2','i3','i4','i5'])

In [133]:
ser_4_vec = pd.Series([101,10,20,50,11],index=['i1','i2','i3','i4','i5'])

In [135]:
ser_3_vec > ser_4_vec

i1    False
i2     True
i3     True
i4     True
i5    False
dtype: bool

In [137]:
ser_5_vec = pd.Series([99,299,399,499,9])
ser_6_vec = pd.Series([101,10,20,50,11])

In [140]:
## both the series were created without index= parameter and as a result, they default to system given indexes
### since both the system indexesin both the series matches, the comparison will work
ser_5_vec > ser_6_vec 

0    False
1     True
2     True
3     True
4    False
dtype: bool

In [141]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) and (ser_3_vec['i3'] < ser_4_vec['i4'])

False

In [142]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) or (ser_3_vec['i3'] < ser_4_vec['i4'])

True

In [143]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) != (ser_3_vec['i3'] < ser_4_vec['i4'])

True

indx    col1 col2  col3 
  1     1     100  200
  2     2     100  300
  3     10    200  500 
  
  1) read from the file 
  2) every row can be a list

# Data Frames in Pandas

- Data frames are 2d data structures .
- Data is aligned in a tabular format consists of rows and columns
- DataFrames can hold multiple data types

- DataFrames Constructor in pandas is
        pd.DataFrames(data=,index=,dtype=,copy)
       
        data holds the data source
        index holds the index to access the data source
        dtype is type of the data
        copy is self to false default. take a copy


In [4]:
import numpy as np
import pandas as pd

In [5]:
#from numpy.random import randn
from numpy.random import randn

In [6]:
np.random.seed(101)   #### this statement gets us the same set of random numbers everytime this notebook session is executed

In [7]:
myrandom_data = randn(5,4)
print(myrandom_data)

[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]


In [8]:
myrandom_data1 = np.random.randn(6,4)

In [24]:
print(myrandom_data1)

[[ 0.39248881  0.22149069 -0.85519604  1.54199041]
 [ 0.66631932 -0.53823463 -0.56858136  1.40733825]
 [ 0.64180551 -0.9050999  -0.39115663  1.02829316]
 [-1.9726051  -0.86688504  0.7207876  -1.22308204]
 [ 1.60677986 -1.11570997 -1.38537856 -1.32966006]
 [ 0.04145994 -0.4110554  -0.7713286   0.11047741]]


In [12]:
#### creating a data frame useing random number generator randn
### we are giubg to use the parameters data, index, columns

mydf = pd.DataFrame(data=myrandom_data, index = ['A','B','C','D','E'], columns=['W','X','Y','Z'])
print(mydf)


##mydf1 = pd.DataFrame(data=myrandom_data, index = ['A','B','C','D','E'], columns=['salespersoname','age','location','productsold'])
#print(mydf1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


##### CREATING A DATA FRAME FROM A LIST


In [13]:
df_list = [['a1','b1','c1'],['a2','b2','c2'],['a3','b3','c3']]
print(df_list)

[['a1', 'b1', 'c1'], ['a2', 'b2', 'c2'], ['a3', 'b3', 'c3']]


In [14]:
#### to create user defined index, let us create a list of index
df_index = ['indx1','indx2','indx3']

In [16]:
mylist_df = pd.DataFrame(data=df_list,index=df_index,columns=('ColA','ColB','Colc'))
print(mylist_df)

      ColA ColB Colc
indx1   a1   b1   c1
indx2   a2   b2   c2
indx3   a3   b3   c3


In [21]:
df_list1 = [['a1','b1','c1'],[100,200,300],['a3',200,99.99]]
mylist_df1 = pd.DataFrame(data=df_list1,index=df_index,columns=('ColA','ColB','Colc'))

print(df_list1)
print(mylist_df1)

[['a1', 'b1', 'c1'], [100, 200, 300], ['a3', 200, 99.99]]
      ColA ColB   Colc
indx1   a1   b1     c1
indx2  100  200    300
indx3   a3  200  99.99


In [23]:
### creating dataframe from a numpy array
import numpy as np
arrtry = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arrtry)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
mylist_df3 = pd.DataFrame(data=arrtry,index=df_index,columns=('ColA','ColB','Colc'))
print(mylist_df3)

       ColA  ColB  Colc
indx1     1     2     3
indx2     4     5     6
indx3     7     8     9


In [150]:
arrtry[0:2,1:3]

array([[2, 3],
       [5, 6]])

- read from a file
- automatically pass it a data frame 
- write code to check size of data frame , store no of rows and columns in variable
