# NumPy Basics By Phalguni Rathod
## Attributes & Functions Notebook

#### Hi, Here we all we do and learn Numpy with hands-on implementaion. This tutorial have have 5 parts as follows:
1. Generation
2. Attributes & Functions
3. Slicing
4. Conditional Selection
5. Operations

In [5]:
import numpy as np

### Setup - Generating array to work with.

In [2]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
ranarr

array([26, 40, 48,  9, 12,  9, 20, 16, 25, 36])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [6]:
ranarr.max()

48

In [7]:
ranarr.min()

9

In [8]:
ranarr.argmax()

2

In [9]:
ranarr.argmin()

3

In [11]:
arr.shape

(25,)

## Reshape
Returns an array containing the same data with a new shape.

In [12]:
ranarr.shape

(10,)

In [13]:
ranarr.reshape((2,5))

array([[26, 40, 48,  9, 12],
       [ 9, 20, 16, 25, 36]])

In [20]:
arr = arr.reshape((5,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.shape

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [23]:
ranarr.dtype

dtype('int32')