# NumPy arrays

In [2]:
import numpy as np

In [0]:
# find out what version we have
np.__version__

'1.16.2'

#### The numpy documentation is crucial!

#### http://docs.scipy.org/doc/numpy/reference/

# Creating arrays

# Manual construction of arrays

# 1-D:

In [0]:
a = np.array([0, 1, 2, 3])

In [0]:
a

array([0, 1, 2, 3])

In [0]:
a.ndim

1

In [0]:
a.shape

(4,)

In [0]:
len(a)

4

# 2-D, 3-D, …:

In [0]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

In [0]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
b.ndim

2

In [0]:
b.shape

(2, 3)

In [0]:
len(b)     # returns the size of the first dimension

2

In [0]:
c = np.array([[[1], [2]], [[3], [4]]])

In [0]:
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [0]:
c.shape

(2, 2, 1)

# Exercise: Simple arrays

Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?
Use the functions len(), numpy.shape() on these arrays. How do they relate to each other? And to the ndim attribute of the arrays?

# Functions for creating arrays

 In practice, we rarely enter items one by one…

# Evenly spaced:

In [5]:
a = np.arange(20) # 0 .. n-1  (!)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
b = np.arange(5,10,2) # start, end (exclusive), step

In [12]:
b

array([5, 7, 9])

# or by number of points:

In [13]:
c = np.linspace(0, 100, 10)   # start, end, num-points

In [14]:
c

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [0]:
d = np.linspace(0, 1, 5, endpoint=False)

In [0]:
d

array([0. , 0.2, 0.4, 0.6, 0.8])

# Common arrays:

In [0]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple

In [0]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
b = np.zeros((2, 2))

In [0]:
b

array([[0., 0.],
       [0., 0.]])

In [0]:
c = np.eye(4)

In [0]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
d = np.diag(np.array([1, 2, 3, 4]))

In [0]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# np.random: random numbers (Mersenne Twister PRNG):

In [21]:
a = np.random.rand(10)       # uniform in [0, 1]

In [22]:
a

array([0.29769553, 0.38089514, 0.46848191, 0.22927069, 0.42225699,
       0.71143208, 0.87848434, 0.18180599, 0.40637133, 0.59409286])

In [23]:
b = np.random.randn(10)      # Gaussian

In [24]:
b

array([ 1.50697012,  1.23488666,  1.28615125,  1.52681455,  0.50851091,
       -0.55006416,  1.61375464, -0.53889157,  1.2801329 , -0.69888686])

In [25]:
np.random.seed(1234)        # Setting the random seed

# Exercise: Creating arrays using functions

Experiment with arange, linspace, ones, zeros, eye and diag.
Create different kinds of arrays with random numbers.
Try setting the seed before creating an array with random values.
Look at the function np.empty. What does it do? When might this be useful?

# 1.3.1.3. Basic data types

You may have noticed that, in some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2). This is due to a difference in the data-type used:

In [0]:
e = np.array([1, 2, 3 , 4])
e.dtype

dtype('int64')

In [0]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

Different data-types allow us to store data more compactly in memory, but most of the time we simply work with floating point numbers. Note that, in the example above, NumPy auto-detects the data-type from the input.

You can explicitly specify which data-type you want:

In [0]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

# The default data type is floating point:

In [0]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

There are also other types:

#### Complex:

In [0]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

#### Bool:

In [0]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

#### Strings:

In [0]:
f = np.array(['Bonjour', 'Hello', 'Hallo'])
f.dtype     # <--- strings containing max. 7 letters 

dtype('<U7')

#### Much more:

In [0]:
int32
int64
uint32
uint64